[project]
name = "text2sql"
version = "0.1.0"
description = ""
authors = [
    {name = "Mikhail Kulyaskin",email = "mihail.ru02@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "langgraph (>=1.0.10,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "langchain (>=1.2.10,<2.0.0)",
    "langchain-openai (>=1.1.10,<2.0.0)",
    "pandas (>=2.2,<3)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "gradio (>=5.49.1,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ipykernel = "^7.2.0"

